### ISSUE TITLE
 CTG fine-tuning dataset with stance and offensive labels

### ISSUE THREAD

**Issue by Jiaxu-Zhao** [abaheti95/ToxiChat#3]
Hi researchers,

Could I have the  CTG fine-tuning dataset in your paper? Thank you !

**Comment by abaheti95** [comment]
Hey,
You can dowload the final threads from [here](https://mega.nz/file/ccwwHSTI#fOOYfM494KqwK6ZaCe9BiuPGZhUKX3QF3CqU0mCTCb8) and copy the entire folder at this location
`data/reddit_dumps/post_comment_threads/CTG_experiments/all_mitigating_sample/final/`.
